### ISSUE TITLE
Create Use Case diagram for System Actors

### ISSUE THREAD

**Issue by ColeMcGregor** [ColeMcGregor/N_Body_Simulation#3]
As a developer, I want to create a Use Case diagram that defines system actors and their interactions with the simulation, so I can clarify system boundaries and roles within the program.

Acceptance Criteria:

1. A Use Case diagram that identifies all primary actors (e.g., user, simulation engine, data storage, visualization module) and their interactions with the system.
2. Detailed use cases that illustrate actions each actor performs within the system, such as starting simulations, accessing data, or visualizing output.
3. Brief descriptions accompanying each use case to clarify purpose and function.

Definition of Done:

1. Use Case diagram created and reviewed, with clear, labeled interactions for each actor.
2. Diagram includes supporting documentation that explains each actor's role and responsibilities within the system.
3. Documentation and diagram are accessible for reference in architectural and development phases.

**Comment by HawkLindner** [comment]
As a user, I want to have a visual representation of our current solar system with the sun, and the 9 planets over the course of hundreds of thousands of years. 

As a user, I want to simulare 2 gravitational masses revolving around each other

As a user, I want to simulate the influence of a Black hole on different masses

As a user, I want to see multiple masses influencing each others orientation in the universe

As a user, I want to see the influence on 2 masses from different distances
